export const menuData = {
  pizza: [
    {
      id: 0,
      sku: "PZ-MAR-001",
      name: "Margherita",
      description: "",
      ingredients: ["tomato sauce", "mozzarella"],
      spicy: false,
      vegetarian: true,
      price: 17.0,
      image: "https://i.imgur.com/8B8YLOo.jpg",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 1,
      sku: "PZ-PEP-002",
      name: "Pepperoni",
      description: "",
      ingredients: ["tomato sauce", "mozzarella", "double pepperoni"],
      spicy: false,
      vegetarian: false,
      price: 20.0,
      image: "https://i.imgur.com/OHHctnf.jpg",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 2,
      sku: "PZ-ROM-003",
      name: "Rome",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "ham",
        "mushrooms",
        "beef cubes",
      ],
      spicy: false,
      vegetarian: false,
      price: 25.75,
      image: "https://i.imgur.com/3ZTwCfz.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 3,
      sku: "PZ-AMS-004",
      name: "American Spicy",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "pepperoni",
        "tomatoes",
        "green pepper",
        "red onion",
        "jalapenos",
        "Samourai sauce",
      ],
      spicy: true,
      vegetarian: false,
      price: 30.25,
      image: "https://i.imgur.com/dyoOLCO.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 4,
      sku: "PZ-QST-005",
      name: "Quattro Stagioni",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "ham",
        "pepperoni",
        "mushrooms",
        "green pepper",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/wOEuXuV.jpg",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 5,
      sku: "PZ-POF-006",
      name: "Pork & Feta",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "feta cheese",
        "ham",
        "pork cubes",
        "red onion",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/48Zw4K3.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 6,
      sku: "PZ-QFO-007",
      name: "Quattro Formaggi",
      description: "",
      ingredients: [
        "mozzarella",
        "cheddar cheese",
        "emmentaler",
        "blue cheese",
        "oregano",
      ],
      spicy: false,
      vegetarian: true,
      price: 35.15,
      image: "https://i.imgur.com/MDrTvkI.jpg",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 7,
      sku: "PZ-CAR-008",
      name: "Carnivora",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "chicken breast",
        "beef cubes",
        "pepperoni",
        "bacon",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/0vPtSSO.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 8,
      sku: "PZ-LCH-009",
      name: "Louisiana Chicken",
      description: "",
      ingredients: [
        "marinated chicken",
        "TABASCO spicy sauce",
        "red pepper sauce",
        "blue cheese",
        "green pepper",
        "red onion",
      ],
      spicy: true,
      vegetarian: false,
      price: 20.0,
      image: "https://i.imgur.com/lZtwJgy.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 9,
      sku: "PZ-HMC-010",
      name: "Honey Mustard Chicken",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "marinated chicken in Honey Mustard sauce",
        "cheddar cheese",
        "red onion",
      ],
      spicy: false,
      vegetarian: false,
      price: 19.8,
      image: "https://i.imgur.com/SoZu61g.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 10,
      sku: "PZ-HAW-011",
      name: "Hawaiian",
      description: "",
      ingredients: [
        "mozzarella",
        "sweet chilli sauce",
        "pepperoni",
        "pineapple",
        "jalapenos",
        "red onion",
      ],
      spicy: true,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/mqTgvgl.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 11,
      sku: "PZ-CLA-012",
      name: "Classic",
      description: "",
      ingredients: ["tomato sauce", "mozzarella", "ham", "mushrooms", "olives"],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/k6IGrUd.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 12,
      sku: "PZ-PAS-013",
      name: "Pastrami",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "pastrami",
        "salty cheese",
        "baked green pepper",
        "red onion",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/yOe5RtC.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 13,
      sku: "PZ-HPA-014",
      name: "Hot Pastrami",
      description: "",
      ingredients: [
        "Honey Mustard sauce",
        "mozzarella",
        "pastrami",
        "sausages",
        "chilli pepper",
        "red onion",
      ],
      spicy: true,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/ipMA5LP.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 14,
      sku: "PZ-COU-015",
      name: "Country",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "bacon",
        "corn",
        "onion",
        "mushrooms",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/E67Xf8Y.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 15,
      sku: "PZ-HCH-016",
      name: "Hot Cheese",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "cheddar cheese",
        "salty cheese",
        "tomatoes",
        "chilli pepper",
        "oregano",
      ],
      spicy: true,
      vegetarian: true,
      price: 27.25,
      image: "https://i.imgur.com/v4sa2cA.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 16,
      sku: "PZ-OCE-017",
      name: "Ocean",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "tuna",
        "corn",
        "onion",
        "olives",
      ],
      spicy: false,
      vegetarian: false,
      price: 30,
      image: "https://i.imgur.com/w5IQ2rX.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 17,
      sku: "PZ-BBQ-018",
      name: "BBQ",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "BBQ sauce",
        "onion",
        "corn",
        "bacon",
        "mushrooms",
        "sausages",
      ],
      spicy: false,
      vegetarian: false,
      price: 28.5,
      image: "https://i.imgur.com/znqS9KD.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 18,
      sku: "PZ-MEX-019",
      name: "Mexicana",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "salsa sauce",
        "pepperoni",
        "corn",
        "onion",
        "jalapenos",
        "tortilla chips",
      ],
      spicy: true,
      vegetarian: false,
      price: 28.5,
      image: "https://i.imgur.com/cYpO8RT.png",
      category: "pizza",
      inStock: true,
      maxQuantity: 10,
    },
  ],
  pasta: [
    {
      id: 0,
      sku: "PA-BOL-001",
      name: "Bolognese",
      description: "",
      ingredients: ["penne", "ragu sauce", "beef cubes", "mozzarella"],
      spicy: false,
      vegetarian: false,
      price: 28.0,
      image: "https://i.imgur.com/IXDJ52k.png",
      category: "pasta",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 1,
      sku: "PA-CAR-002",
      name: "Carbonara",
      description: "",
      ingredients: [
        "penne",
        "white cream and garlic sauce",
        "bacon",
        "parmesan",
      ],
      spicy: false,
      vegetarian: false,
      price: 28.0,
      image: "https://i.imgur.com/3jKSuUu.png",
      category: "pasta",
      inStock: true,
      maxQuantity: 10,
    },
  ],
  salads: [
    {
      id: 0,
      sku: "SA-CAE-001",
      name: "Caesar",
      description: "",
      ingredients: [
        "chicken breast",
        "bacon",
        "parmesan",
        "cherry tomatoes",
        "croutons",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: false,
      price: 20,
      image: "https://i.imgur.com/QWXH2NC.png",
      category: "salads",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 1,
      sku: "SA-GRE-002",
      name: "Greek",
      description: "",
      ingredients: [
        "feta cheese",
        "green olives",
        "cherry tomatoes",
        "cucumbers",
        "red onion",
        "red pepper",
        "oregano",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: true,
      price: 20,
      image: "https://i.imgur.com/qChqf83.png",
      category: "salads",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 2,
      sku: "SA-TUN-003",
      name: "Tuna",
      description: "",
      ingredients: [
        "tuna",
        "green olives",
        "corn",
        "red pepper",
        "red onion",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: false,
      price: 20,
      image: "https://i.imgur.com/Ph0IjrX.png",
      category: "salads",
      inStock: true,
      maxQuantity: 10,
    },
  ],
  dessert: [
    {
      id: 0,
      sku: "DE-BRO-001",
      name: "Brownie",
      description: "A delicious cake with chocolate and hazelnuts",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 15,
      image: "https://i.imgur.com/7WbfaDN.png",
      category: "dessert",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 1,
      sku: "DE-CHT-002",
      name: "Chocolate Tortilla",
      description: "Tortilla filled with chocolate cream",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 12,
      image: "https://i.imgur.com/Mgsc3IZ.png",
      category: "dessert",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 2,
      sku: "DE-APP-003",
      name: "Apple Pie",
      description: "Hot pie with apple and cinnamon",
      ingredients: [],
      spicy: false,
      vegetarian: true,
      price: 15,
      image: "https://i.imgur.com/OWIVhWX.png",
      category: "dessert",
      inStock: true,
      maxQuantity: 10,
    },
    {
      id: 3,
      sku: "DE-CHE-004",
      name: "Cheesecake",
      description: "Cheesecake with berries topping",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 15,
      image: "https://i.imgur.com/AsldA7x.png",
      category: "dessert",
      inStock: true,
      maxQuantity: 10,
    },
  ],
  drinks: [
    {
      id: 0,
      sku: "DR-COC-001",
      name: "Coca Cola",
      description: "Coca Cola 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/nJ6LeWv.png",
      category: "drinks",
      inStock: true,
      maxQuantity: 15,
    },
    {
      id: 1,
      sku: "DR-FAN-002",
      name: "Fanta",
      description: "Fanta 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/1WDkfme.png",
      category: "drinks",
      inStock: true,
      maxQuantity: 15,
    },
    {
      id: 2,
      sku: "DR-SPR-003",
      name: "Sprite",
      description: "Sprite 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/qP4Nx1x.jpg",
      category: "drinks",
      inStock: true,
      maxQuantity: 15,
    },
    {
      id: 3,
      sku: "DR-WAT-004",
      name: "Water",
      description: "Dorna 0.5L",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4.5,
      image: "https://i.imgur.com/yYuuaL1.jpg",
      category: "drinks",
      inStock: true,
      maxQuantity: 20,
    },
    {
      id: 4,
      sku: "DR-SPA-005",
      name: "Sparkling water",
      description: "Dorna 0.5L",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4.5,
      image: "https://i.imgur.com/0nyJk19.jpg",
      category: "drinks",
      inStock: true,
      maxQuantity: 20,
    },
    {
      id: 5,
      sku: "DR-FUZ-006",
      name: "Fuzetea",
      description: "Fuzetea 0.5L Peach or Lemon",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/dsHumXE.jpg",
      category: "drinks",
      inStock: true,
      maxQuantity: 15,
    },
  ],
};
